[book]
authors = ["Ankitects Pty Ltd and contributors"]
description = "Anki Kurulum ve Kullanım Kılavuzu. Anki öğrenmeyi kolaylaştıran bir flashcard uygulamasıdır"
language = "tr"
multilingual = false
src = "src"
title = "Anki Kurulum ve Kullanım Kılavuzu "

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/ankitects/anki-manual/" #will update 
cname = "docs.ankiweb.net" #will update
additional-css = ["css/misc.css", "css/kbd.css"]
mathjax-support = true

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
exclude = [
  'microsoft.com',
  'twitter.com',
  'stackexchange.com',
  'stackoverflow.com',
  'https://github.com/open-spaced-repetition/fsrs4anki#add-on-compatibility',
  'support.google.com',
  'wikiwiki.jp',
  'web.archive.org',
]

[output.html.fold]
enable = true
level = 0
